<?php

/************************** Custom Template *****************************/

return array(
	'name'              => esc_attr__( 'About 1', 'fablio' ),    // Template Title
	'template_category' => esc_attr__( 'About', 'fablio' ),	 // Template Category
	'content'           => '<<<TMCONTENTTILLTHIS
[vc_row tm_bgimagefixed="" break_in_responsive="991" css=".vc_custom_1616568844572{margin-top: -12px !important;padding-top: 0px !important;padding-bottom: 150px !important;}" tm_responsive_css="72223674|colbreak_no|||||||||colbreak_no|||||||0px||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="5/12"][vc_row_inner css=".vc_custom_1615877091941{padding-right: 86px !important;padding-left: 54px !important;}" tm_responsive_css="21412677|colbreak_no|||||||||colbreak_no|||15px|||0px||0px|colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner tm_bgcolor="grey" css=".vc_custom_1615876963709{margin-top: -70px !important;padding-top: 80px !important;padding-right: 35px !important;padding-left: 35px !important;}" tm_responsive_css="51391839|colbreak_no|||||||||colbreak_no|||||25px|15px||15px|colbreak_no||||||||||colbreak_no|||||||||"][tm-heading h2="Ultimate Quality <b>Textiles</b>" seperator="none"][/tm-heading][vc_column_text css=".vc_custom_1614851452424{margin-top: -22px !important;margin-bottom: 37px !important;}"]We are your reliable and experienced textile partner around the world.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1615878786389{margin-right: 15px !important;padding-bottom: 0px !important;}" tm_responsive_css="19576919|colbreak_no|||||||||colbreak_no||-15px|||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner el_class="tm-custome-center-video-icon"][vc_single_image image="1345" img_size="full" el_class="tm-img-hoverstyle1"][tm-icon type="fontawesome" icon_fontawesome="fa fa-play" color="white" background_style="rounded" background_color="skincolor" align="center" el_class="tm_prettyphoto style2" link="url:https%3A%2F%2Fyoutu.be%2F7e90gBu4pas"][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1615878343173{margin-top: 0px !important;padding-top: 0px !important;padding-right: 98px !important;padding-left: 40px !important;}" tm_responsive_css="36608444|colbreak_no|||||||||colbreak_no|15px|||||0px||0px|colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner tm_bgcolor="grey" css=".vc_custom_1615878368396{margin-top: -35px !important;margin-right: 10px !important;margin-left: 13px !important;padding-top: 30px !important;}" tm_responsive_css="99635083|colbreak_no|||||||||colbreak_no||0px||0px|||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_text]
<p style="text-align: center;">The Largest Exporter of <a href="https://themetechmount.com/wordpress/fablio/services1/"><u style="color: #c3002f;">Textile</u></a></p>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="7/12" css=".vc_custom_1613990024895{padding-top: 10px !important;}"][vc_row_inner break_in_responsive="991" equal_height="yes" el_class="tm-col-seprator" tm_responsive_css="65786530|colbreak_no|||||||||colbreak_no|||||10px||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner width="1/2" css=".vc_custom_1615271889081{padding-bottom: 15px !important;}"][tm-iconbox h2="Fablio Overview" i_type="kw_fablio" i_icon_kw_fablio="kw_fablio flaticon-factory" show_btn="yes" btn_title="Read More" css=".vc_custom_1616048419356{margin-bottom: 0px !important;}" btn_link="url:https%3A%2F%2Fthemetechmount.com%2Fwordpress%2Ffablio%2Fservice%2Ffabric-printing%2F"]We Bringing a revolutionary change in the Textile industry through products![/tm-iconbox][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1615878906476{padding-bottom: 15px !important;padding-left: 45px !important;}" tm_responsive_css="77506068|colbreak_no|||||||||colbreak_no|-20px|||||||15px|colbreak_no||||||||||colbreak_no|||||||||"][tm-iconbox h2="Production Capability" i_type="kw_fablio" i_icon_kw_fablio="kw_fablio flaticon-suit" show_btn="yes" btn_title="Read More" css=".vc_custom_1616048429308{margin-bottom: 0px !important;}" btn_link="url:https%3A%2F%2Fthemetechmount.com%2Fwordpress%2Ffablio%2Fservice%2Ffabric-printing%2F"]Were try to be not just legally compliant but more than that.
[/tm-iconbox][/vc_column_inner][/vc_row_inner][vc_separator color="custom" css=".vc_custom_1615879482100{margin-bottom: 0px !important;}" accent_color="#eeeeee" el_class="tm-hide991px"][vc_row_inner break_in_responsive="991" equal_height="yes" el_class="tm-col-seprator" css=".vc_custom_1615879758677{padding-top: 1px !important;}" tm_responsive_css="46831117|colbreak_no|||||||||colbreak_no|-35px||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner width="1/2" css=".vc_custom_1614836731819{padding-top: 25px !important;}"][tm-iconbox h2="Company History" i_type="kw_fablio" i_icon_kw_fablio="kw_fablio flaticon-warehouse" show_btn="yes" btn_title="Read More" btn_link="url:https%3A%2F%2Fthemetechmount.com%2Fwordpress%2Ffablio%2Fservice%2Ffabric-printing%2F" css=".vc_custom_1616048443149{margin-bottom: 10px !important;}"]One of the largest &amp; most reputed textile groups in India &amp; globe.
[/tm-iconbox][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1615878967004{padding-top: 25px !important;padding-left: 45px !important;}" tm_responsive_css="46077691|colbreak_no|||||||||colbreak_no|-15px||||0px|||15px|colbreak_no||||||||||colbreak_no|||||||||"][tm-iconbox h2="Fabric Designs" i_type="kw_fablio" i_icon_kw_fablio="kw_fablio flaticon-fabric" show_btn="yes" btn_title="Read More" btn_link="url:https%3A%2F%2Fthemetechmount.com%2Fwordpress%2Ffablio%2Fservice%2Ffabric-printing%2F" css=".vc_custom_1616048453532{margin-bottom: 10px !important;}"]Gold trophy 5 years in a row for being the largest exporter
[/tm-iconbox][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
TMCONTENTTILLTHIS',
);
